[1.8 release] Switch to translation dataset in torchtext 0.9.0 release
pytorch/tutorials pull request #1351
Opened 2021-02-09 21:51 UTC by zhangguanheng66

In torchtext 0.9.0 release, we will include the raw text datasets as beta release. This PR is to switch the data to the raw dataset.

This PR should be tested against pytorch 1.8.0 rc and torchtext 0.9.0 rc.

2021-02-09 21:52 UTC, zhangguanheng66 commented
We expect the CI tests to fail until we switch to 1.8.0-rc.
cc @brianjo @cpuhrsch

2021-02-09 22:18 UTC, cpuhrsch commented on beginner_source/torchtext_translation.py
> +train_iter, = Multi30k(split=('train'))
We should add support for a single string for this release as well, i.e.
```
train_iter = Multi30k(split='train')
```
I'll send a PR to torchtext.

2021-02-18 23:23 UTC, cpuhrsch commented on beginner_source/torchtext_translation.py
> +train_iter, = Multi30k(split=('train'))
We now have support for a single string argument. I'd prefer if we used that one.

2021-02-24 00:11 UTC, cpuhrsch requested changes
Since Multi30k is being moved into experimental for this release, let's pick a different translation dataset, for example one of the IWSLT datasets.

2021-02-24 01:21 UTC, zhangguanheng66 commented
Switch to IWSLT2017

2021-02-24 01:29 UTC, cpuhrsch reviewed
The tutorial itself still has code such as

```
# ENC_EMB_DIM = 256
# DEC_EMB_DIM = 256
# ENC_HID_DIM = 512
# DEC_HID_DIM = 512
# ATTN_DIM = 64
# ENC_DROPOUT = 0.5
# DEC_DROPOUT = 0.5
```

Did you also confirm that the model converges to something meaningful under this new dataset?

2021-02-24 01:52 UTC, zhangguanheng66 commented
> The tutorial itself still has code such as
> 
> ```
> # ENC_EMB_DIM = 256
> # DEC_EMB_DIM = 256
> # ENC_HID_DIM = 512
> # DEC_HID_DIM = 512
> # ATTN_DIM = 64
> # ENC_DROPOUT = 0.5
> # DEC_DROPOUT = 0.5
> ```
> 
> Did you also confirm that the model converges to something meaningful under this new dataset?

I'm adjusting the amount of data used in this tutorial as IWSLT2017 has more data than Multi30k

2021-02-24 17:29 UTC, cpuhrsch requested changes
Given the issues with convergence on this IWSLT2017 and the release of Multi30k being delayed, let's not release an update to this tutorial.

2021-02-24 18:39 UTC, zhangguanheng66 commented
Since `Multi30k` dataset is not going to be released in torchtext v0.9.0 - https://github.com/pytorch/text/pull/1207, we will delay this PR until we release `Multi30k`.

2024-10-26 00:15 UTC, closed without merging