update quantization tutorial by introudcing x86 backend
pytorch/tutorials pull request #2081
Opened 2022-10-13 10:05 UTC by XiaobingSuper

2022-10-13 10:15 UTC, jgong5 requested changes

2022-10-13 10:15 UTC, jgong5 commented on beginner_source/vt_tutorial.py
> +# Use 'x86' for server inference (th old 'fbgemm' is still available but 'x86' is the recommended default) and 'qnnpack' for mobile inference.
```suggestion
# Use 'x86' for server inference (the old 'fbgemm' is still available but 'x86' is the recommended default) and 'qnnpack' for mobile inference.
```

2022-10-14 19:54 UTC, vkuzo commented
cc @jerryzh168 , do we know the status of the x86 issues with respect to PyTorch v1.13?  Did we cherry-pick backing out the x86 as default, and do we have a timeline on fix to x86 backend?

2022-10-14 21:17 UTC, jerryzh168 commented
> cc @jerryzh168 , do we know the status of the x86 issues with respect to PyTorch v1.13? Did we cherry-pick backing out the x86 as default, and do we have a timeline on fix to x86 backend?

in PyTorch 1.13 we have reverted back to using fbgemm as default backend. cherry-pick is merged: https://github.com/pytorch/pytorch/issues/86312#issuecomment-1275329963

I'm trying out the fix now: https://github.com/pytorch/pytorch/pull/86876

2022-10-14 21:18 UTC, jerryzh168 requested changes
let's wait until the problem is resolved

2023-02-01 19:39 UTC, jerryzh168 approved these changes
thanks, looks like there are some broken ci tests, please make sure everything is green before landing

2023-02-03 02:17 UTC, XiaobingSuper commented
@jerryzh168, please help merge it,

2023-02-06 18:35 UTC, jerryzh168 commented
@svekars can you help merging this? I'm not sure how to merge tutorial PRs

2023-02-07 20:17 UTC, svekars commented
@XiaobingSuper Hello, can you please provide some context around this change? As far as I understand this change is for the PyTorch release 2.0. We typically merge such PRs on the day of the release because we don't version tutorials. I'm not seeing any issues at the moment and I will also run this PR against the RC branch when it becomes available. No actions needed on your side as of now. Does this sound good?

2023-02-08 01:53 UTC, XiaobingSuper commented
@svekars , yes, this is for PyTorch 2.0, we introduced this feature for [Unified quantization backend for x86 CPU platforms](https://github.com/pytorch/pytorch/issues/83888). it is ok to merge this PR on the 2.0 release data, thanks!

2023-03-02 04:36 UTC, XiaobingSuper commented
@svekars , is it ready to merge this PR for PT 2.0 release? Thanks!

2023-03-02 18:10 UTC, msaroufim approved these changes
Looks good but might be worth explaining in a few sentences to users why the new x86 backend is better

2023-03-03 00:30 UTC, jgong5 reviewed
@msaroufim Thanks for the review and suggestion. I added a suggest edit to one of the changes to elaborate on the benefit. Does that sound good to you? If so, is it fine to add this to all the changes?

2023-03-03 00:30 UTC, jgong5 commented on recipes_source/quantization.rst
> +  To make the model run on mobile devices which normally have arm architecture, you need to use `qnnpack` for `backend`; to run the model on computer with x86 architecture, use `x86`` (the old `fbgem
```suggestion
  To make the model run on mobile devices which normally have arm architecture, you need to use `qnnpack` for `backend`; to run the model on computer with x86 architecture, use `x86`` (the old `fbgemm` is still available but 'x86' is the recommended default which leverages the goodness of both oneDNN and fbgemm libraries and runs faster).
```

2023-03-15 23:20 UTC, merged