Introduction of Quadric Layers - Action triggered by Ankith Gunapal
pytorch/tutorials pull request #2520
Opened 2023-08-04 16:06 UTC by diro5t

This is a small tutorial for quadric layers as it pertains to the feature list of PyTorch 2.1. Ankith asked me to provide a small tutorial for this.

2023-08-04 17:18 UTC, agunapal requested changes
@diro5t Thanks for the PR. Looks good overall. It would be great to show the reduction in model size in the tutorial.
Can you please sign the CLA too.

2023-08-04 17:18 UTC, agunapal commented on intermediate_source/quadric_layers_tutorial.py
> +# Quadric layers can easily be used to reduce model size in many applications just by replacing linear layers.
Can we show the reduction in model size in this tutorial, (before vs after)

2023-08-04 17:18 UTC, agunapal commented on intermediate_source/quadric_layers_tutorial.py
> +        print("Epoch {} - Training loss: {}".format(e, train_loss/len(train_loader)))
Nit: f-strings would be nice

2023-08-04 17:21 UTC, agunapal commented
cc: @msaroufim

2023-08-06 00:55 UTC, msaroufim approved these changes
this was fun to learn about thanks! Appreciated that you showed how it was a dropin replacement for `nn.Linear()`

2023-08-06 02:22 UTC, diro5t commented
Thanks, I hope a lot of interested people will try it out in all kinds of applications--best regardsDirk RoeckmannFive Troop Consulting Services ***@***.*** Aug 5, 2023, at 8:55 PM, Mark Saroufim ***@***.***> wrote:﻿
@msaroufim approved this pull request.

this was fun to learn about thanks! Appreciated that you showed how it was a dropin replacement for nn.Linear()

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-08-06 02:50 UTC, agunapal approved these changes
Looks good to me. Thanks

2023-08-08 22:05 UTC, svekars reviewed
Thanks so much! Some editorial suggestion here. Please let me know if you have any questions. Also please review the following:
* Spellcheck is [failing](https://github.com/pytorch/tutorials/actions/runs/5766975285/job/15635921009?pr=2520). Words like quadric, Quadric can be added to the [en-wordlist.txt](https://github.com/pytorch/tutorials/blob/main/en-wordlist.txt).
*  Need to add your tutorial as a ``customcarditem `` and to the appropriate ``toctree`` in [index.rst](https://github.com/pytorch/tutorials/blob/main/index.rst).
* We will be targeting to run this against the PyTorch 2.1 RC and merging on the day of the 2.1 release in October.

2023-08-08 22:05 UTC, svekars commented on intermediate_source/quadric_layers_tutorial.py
> +#
Please add a conclusion section. For example:

Conclusion
-------------

In this tutorial, you have learned .....<add more text here>
For more information, see: 

* link1
* link2
* link3

2023-08-08 22:05 UTC, svekars commented on intermediate_source/quadric_layers_tutorial.py
> +# `here <https://github.com/pytorch/pytorch/issues>` if you have any.
```suggestion
```

2023-08-09 18:54 UTC, mikaylagawarecki requested changes
Hey, it seems like this was prompted by the prototype feature request for torch.nn.Quadric in 2.1 that was submitted for it. 

Let's wait until we have a conclusion on the associated issue  https://github.com/pytorch/pytorch/issues/105365 before we land this tutorial

2023-08-09 20:25 UTC, diro5t commented
> Hey, it seems like this was prompted by the prototype feature request for `torch.nn.Quadric` that was submitted for 2.1.
> 
> Let's wait until we have a conclusion on the associated issue [pytorch/pytorch#105365](https://github.com/pytorch/pytorch/issues/105365) before we land this tutorial


Does this mean, I should not apply the proposed changes for now? Please advise

2024-04-19 18:53 UTC, closed without merging