Create ONNX section with sattic URL
pytorch/tutorials pull request #2550
Opened 2023-09-06 22:25 UTC by thiagocrepaldi

2023-09-07 18:17 UTC, thiagocrepaldi commented
https://github.com/pytorch/tutorials/pull/2541/ will be added to this page as soon as it can be merged

2023-09-07 20:20 UTC, thiagocrepaldi commented
@msaroufim FYI

2023-09-07 21:19 UTC, msaroufim requested changes
I'm generally OK with having a `tutorials/onnx` but having onnx be a in the left hand navigation is not something I'm as excited about since I'd then have to also be OK with other compiler vendors doing the same

Is there any way we can roll this content in to the deployment tab?

2023-09-08 16:51 UTC, thiagocrepaldi commented
> I'm generally OK with having a `tutorials/onnx` index page but having onnx be a in the left hand navigation is not something I'm as excited about since I'd then have to also be OK with other compiler vendors doing the same
> 
> Is there any way we can roll this content in to the deployment tab?

If we could have submenus under `Deploying PyTorch Models in Production` menu, that probably would help already, but I think this is not a trivial task by quickly going through the code. That is why we proposed a ONNX menu on its own.

We do understand the duality of ONNX, especially after pytorch 2.x series. On one hand, `torch.onnx` is within pytorch project under the github.com/pytorch umbrella, like torchvision, torchtext, and torchaudio. Each of these other pytorch components have a menu on their own. From this point of view, ONNX module as pytorch's component could have a menu on its own. On the other hand, after pt 2.0 the concept of dynamo backends got generalized and vendors started implementing theirs and adding all of them might be tricky. 

Also, because we introduced a new ONNX exporter based on Dynamo (`torch.onnx.dynamo_export`) but we still support the older one based on TorchScript (`torch.onnx.export`), we plan in having tutorials helping on the decision-making process of which one to use, which wouldn't be a "deployment" tutorial per se, but very related. Other related but not exactly deployment might be 1) migration process from the TorchScript to the Dynamo based exporter and 2) working around limitations of the exporter, helping users to fix their model for successful export. There is a whole bunch of ONNX-related tutorials to cover lack of documentation of the previous exporter that we plan that may not fit directly into the "deployment" umbrella and having them sprinkled in different menus would be a bit messy

I hope that helps making our case :)

2023-09-12 18:00 UTC, thiagocrepaldi commented
Changed the left menu to `Backends` instead of `ONNX` as per offline discussion with @svekars

2023-09-12 18:36 UTC, msaroufim commented
Ping me when the doc renders I still don't see the most recent changes

2023-09-13 06:20 UTC, msaroufim approved these changes

2023-09-13 06:20 UTC, msaroufim commented
ok just stamped thanks!

2023-09-13 15:04 UTC, svekars commented
Thanks! I will do an editorial pass. We will merge all 2.1 tutorials on the day of the release.

2023-09-13 15:39 UTC, svekars approved these changes
LGTM, just a couple of nits.

2023-09-13 15:39 UTC, svekars commented on beginner_source/onnx/intro_onnx.py
> +    Currently there are two flavors of ONNX exporter APIs,
```suggestion
    Currently, there are two flavors of ONNX exporter APIs,
```

2023-09-13 15:45 UTC, thiagocrepaldi commented
> LGTM, just a couple of nits.

nits fixed

2023-09-14 15:35 UTC, svekars commented on .jenkins/validate_tutorials_built.py
> +    "beginner_source/onnx/intro_onnx",
```suggestion
    "beginner_source/onnx/intro_onnx", # has no usable code and serves as a landing for ONNX tutorials
```

2023-10-04 15:33 UTC, svekars approved these changes

2023-10-04 15:33 UTC, merged