edited cifar10_tutorial.py
pytorch/tutorials pull request #2604
Opened 2023-10-12 16:51 UTC by anikethc

Fixes #792 

## Description
I've set the code blocks to be non-executable. However, the sections titled "2. Define a Convolution Neural Network" and "3. Define a Loss function and optimizer" should retain their executability to ensure error-free execution. I've also cleaned up the code by removing extraneous symbols , fixed the imaged which was not being rendered correctly and made the links clickable.

2023-10-12 16:59 UTC, anikethc commented
Hi @svekars,
I've made some changes and would appreciate it if you could review them. Thanks!

2023-10-12 19:24 UTC, malfet requested changes
Please restrict your PR to one fix at the time and perhaps add before and after picture

For example https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html already renders pictures correctly and links are already clickable, so I'm a bit confused why change to the link formatting/ image rendering are necessary

2023-10-12 19:24 UTC, malfet commented on beginner_source/blitz/cifar10_tutorial.py
> +![](https://pytorch.org/tutorials/_images/cifar10.png)
Why this is needed? (I.e. keeping it as is allows one to re-host the repository anywhere they want, isn't it?)

2023-10-12 23:53 UTC, anikethc commented
Sorry I will keep that in mind for next issue. I was referring to the colab file the image isnt rendering correctly and all the link are unclickable in the colab https://colab.research.google.com/github/pytorch/tutorials/blob/gh-pages/_downloads/cifar10_tutorial.ipynb#scrollTo=N1BibYLW8C4N .

2023-10-13 02:11 UTC, malfet commented
@anikethc at the very least, .py files should remain valid executable files, which is not the case after your changes, is it?

2023-10-13 03:51 UTC, anikethc commented
Everything was working fine when I executed the ipynb in the google colab https://colab.research.google.com/drive/1GOhFgmRs-nMF9W7eJjcmBahk6SbBJLXS?usp=sharing maybe something went wrong when I converted it into .py file. I will look into it. Thank you for being patient with me.

2023-11-04 23:02 UTC, anikethc commented
Hi @malfet , Could you please review the commit.

2023-11-05 17:59 UTC, malfet requested changes
Can you please restrict this PR to just making blogs non-executable?

I.e. the convention throughout the tutorials are to use rst markup convention, not HTML one, which makes lots of `<IMG` and `<A HREF` changes wrong. I understand that they do not render in the collab notebook correctly, but this probably tells something about converter pipeline

2024-10-27 00:17 UTC, closed without merging