Update parametrizations.py
pytorch/tutorials pull request #2642
Opened 2023-11-03 22:49 UTC by ahoblitz

For PyTorch 2, torch.solve => torch.linalg.solve

Fixes #2641 https://github.com/pytorch/tutorials/issues/2641

## Description
Code like
`    def forward(self, X):`
 `       # (I + X)(I - X)^{-1}`
`        return torch.solve(self.Id + X, self.Id - X).solution`
results in
`RuntimeError: This function was deprecated since version 1.9 and is now removed. torch.solve is deprecated in favor of torch.linalg.solve. torch.linalg.solve has its arguments reversed and does not return the LU factorization.`

Update to use `pytorch.linalg.solve`

## Checklist

- [ ] The issue that is being fixed is referred in the description (see above "Fixes #ISSUE_NUMBER")
- [ ] Only one issue is addressed in this pull request
- [ ] Labels from the issue that this PR is fixing are added to this pull request
- [ ] No unnecessary issues are included into this pull request.

2023-11-03 22:55 UTC, svekars approved these changes
LGTM! Thanks for catching this.

2023-11-03 23:08 UTC, malfet approved these changes

2023-11-03 23:12 UTC, malfet requested changes
As warning correctly mentions, you need to change argument order

2023-11-03 23:12 UTC, svekars commented on intermediate_source/parametrizations.py
> +        return torch.linalg.solve(self.Id + X, self.Id - X)
```suggestion
        return torch.linalg.solve(self.Id - X, self.Id + X)
```

2023-11-03 23:18 UTC, malfet commented on intermediate_source/parametrizations.py
> +        return torch.linalg.solve(self.Id + X, self.Id - X)
```suggestion
        return torch.linalg.solve(self.Id - X, self.Id + X)
```

2023-11-03 23:18 UTC, malfet commented on intermediate_source/parametrizations.py
> +        return torch.linalg.solve(X - self.Id, self.Id + X)
```suggestion
        return torch.linalg.solve(X + self.Id, self.Id - X)
```

2023-11-04 00:19 UTC, malfet approved these changes

2023-11-04 00:39 UTC, merged