Added tutorials for Holistic Trace Analysis
pytorch/tutorials pull request #2723
Opened 2023-12-28 21:51 UTC by anupambhatnagar

Fixes #ISSUE_NUMBER

## Description
- Added two tutorials for HTA
  - Introduction to HTA
  - TraceDiff using HTA
- Created a left panel entry called "Profiling PyTorch" which now contains the introductory `

## Checklist

- [ ] The issue that is being fixed is referred in the description (see above "Fixes #ISSUE_NUMBER")
- [ ] Only one issue is addressed in this pull request
- [ ] Labels from the issue that this PR is fixing are added to this pull request
- [ ] No unnecessary issues are included into this pull request.

2023-12-28 22:18 UTC, aaronenyeshi requested changes

2023-12-28 22:18 UTC, aaronenyeshi commented on requirements.txt
this looks like a temp change not meant to land

2023-12-28 22:23 UTC, aaronenyeshi reviewed
Overall looks great!

2023-12-28 22:34 UTC, anupambhatnagar commented on requirements.txt
yup, fixing it.

2023-12-30 00:39 UTC, malfet approved these changes
LGTM, not sure if `beginner` folder is the right one for it, as other profiling tutorials are in the intermediate, aren't they?

2024-01-02 23:02 UTC, anupambhatnagar commented
> LGTM, not sure if `beginner` folder is the right one for it, as other profiling tutorials are in the intermediate, aren't they?

There are two tutorials tagged with profiling. One of them is in beginner and the other one is in intermediate. These are introductory HTA tutorials so I placed them in the beginners folder.

2024-01-02 23:03 UTC, merged