Revamp TorchRec intro tutorial
pytorch/tutorials pull request #3064
Opened 2024-09-27 19:34 UTC by PaulZhang12

## Description
Revamps TorchRec tutorial for stable release

2024-09-27 20:08 UTC, svekars requested changes

2024-09-27 20:08 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +#
```suggestion
```

2024-09-27 22:43 UTC, svekars commented on .jenkins/metadata.json
> +  },
```suggestion
  }
```

2024-09-27 22:44 UTC, svekars commented on .jenkins/metadata.json
> +  }
```suggestion
  },
```

2024-09-30 15:29 UTC, PaulZhang12 commented on .ci/docker/requirements.txt
> +torchrec
We can do torchrec==0.8 for now, and change to 1.0 once it's out?

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# ```EmbeddingBagCollectionSharder`` <https://pytorch.org/torchrec/torchrec.distributed.html#torchrec.distributed.embeddingbag.EmbeddingBagCollectionSharder>`__
```suggestion
#    * For ``EmbeddingBagCollection``, the sharder is
# `EmbeddingBagCollectionSharder <https://pytorch.org/torchrec/torchrec.distributed.html#torchrec.distributed.embeddingbag.EmbeddingBagCollectionSharder>`__
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# 2. Sharded module: This class is a sharded variant of a TorchRec module.
```suggestion
# 2. **Sharded module:** This class is a sharded variant of a TorchRec module.
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# EmbeddingBagCollection, will handle everything that is needed for Model
```suggestion
# ``EmbeddingBagCollection``, will handle everything that is needed for Model
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# Refresher of our EmbeddingBagCollection module
```suggestion
# Refresher of our ``EmbeddingBagCollection`` module
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +
```suggestion
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# 2 embedding tables and 2 GPUs, you can: \* Place 1 table on each GPU \*
```suggestion
# 2 embedding tables and 2 GPUs, you can:
# 
# * Place 1 table on each GPU
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# Place both tables on a single GPU and no tables on the other \* Place
```suggestion
# * Place both tables on a single GPU and no tables on the other
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# certain rows/columns on each GPU
```suggestion
# * Place certain rows and columns on each GPU
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# given the # of embedding tables and the # of GPUs, what is the optimal
```suggestion
# given the number  of embedding tables and the number of GPUs, what is the optimal
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# plan.
> 
```suggestion
# the planner is used.
#
# The TorchRec planner: 
#
# * Assesses memory constraints of hardware
# * Estimates compute based on memory fetches as embedding lookups
# * Addresses data specific factors
# * Considers other hardware specifics like bandwidth to generate an optimal sharding plan.
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# routinely provided across stacks
```suggestion
# routinely provided across stacks.
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# As you can see, when running the planner there is quite a bit of output
```suggestion
# As you can see above, when running the planner there is quite a bit of output.
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# above. We can see a ton of stats being calculated along with where our
```suggestion
# We can see a lot of stats being calculated along with where our
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# Shard the EmbeddingBagCollection module using the EmbeddingBagCollectionSharder
> 
```suggestion
# Shard the ``EmbeddingBagCollection`` module using the ``EmbeddingBagCollectionSharder``
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# Awaitable
```suggestion
# ``Awaitable``
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# ^^^^^^^^^
```suggestion
# ^^^^^^^^^^^^^^^^^^^^^^
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# Demonstrate a LazyAwaitable type
```suggestion
# Demonstrate a ``LazyAwaitable`` type:
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# We have now successfully sharded an EmbeddingBagCollection given a
> 
```suggestion
# We have now successfully sharded an ``EmbeddingBagCollection`` given a
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# 1. **input\_dist**: Handles distributing inputs from GPU to GPU
```suggestion
# * ``input_dist``: Handles distributing inputs from GPU to GPU.
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# 2. **lookups**: Does the actual embedding lookup in an optimized,
```suggestion
# * ``lookups``: Does the actual embedding lookup in an optimized,
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +#    batched manner using FBGEMM TBE (more on this later)
```suggestion
#    batched manner using FBGEMM TBE (more on this later).
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# 3. **output\_dist**: Handles distributing outputs from GPU to GPU
```suggestion
# * ``output_dist``: Handles distributing outputs from GPU to GPU
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# The distribution of inputs/outputs is done through `NCCL
```suggestion
# The distribution of inputs and outputs is done through `NCCL
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# which is where all GPUs send/receive data to and from one another.
```suggestion
# which is where all GPUs send and receive data to and from one another.
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# order for distribution of gradients. input\_dist, lookup, and
```suggestion
# order for distribution of gradients. ``input_dist``, ``lookup``, and
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# output\_dist all depend on the sharding scheme. Since we sharded in a
```suggestion
# ``output_dist`` all depend on the sharding scheme. Since we sharded in a
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +ebc
does it need ebc?

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# Congrats!
```suggestion
# Conclusion
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# You have now gone from training a distributed RecSys model all the way
```suggestion
# In this tutorial, you have gone from training a distributed RecSys model all the way
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# https://github.com/pytorch/torchrec/tree/main/torchrec/inference has a
```suggestion
# The `TorchRec repo <https://github.com/pytorch/torchrec/tree/main/torchrec/inference>`__  has a
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# example, which includes multinode training on the criteo terabyte
```suggestion
# example, which includes multinode training on the Criteo 1TB
```

2024-10-01 17:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# dataset, using Meta’s `DLRM <https://arxiv.org/abs/1906.00091>`__.
```suggestion
# dataset using the methods described in `Deep Learning Recommendation Model for Personalization and Recommendation Systems (DLRM) <https://arxiv.org/abs/1906.00091>`__.
```

2024-10-01 20:28 UTC, svekars commented on en-wordlist.txt
> +Meta's
can you run the sort command in vim (`:sort`), so it's sorted alphabetically.

2024-10-01 20:48 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# `torch.nn.Embedding <https://pytorch.org/docs/stable/generated/torch.nn.Embedding.html>`__:
```suggestion
# :class:`torch.nn.Embedding`:
```

2024-10-01 20:49 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# `torch.nn.EmbeddingBag <https://pytorch.org/docs/stable/generated/torch.nn.EmbeddingBag.html>`__:
```suggestion
# :class:`torch.nn.EmbeddingBag`:
```

2024-10-02 15:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +
```suggestion
```

2024-10-02 15:20 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +#   !pip3 install --pre torch --index-url https://download.pytorch.org/whl/cu121 -U
```suggestion
#
#   !pip3 install --pre torch --index-url https://download.pytorch.org/whl/cu121 -U
```

2024-10-02 16:04 UTC, svekars commented on intermediate_source/torchrec_interactive_tutorial.py
> +# In the secion above we've learned how to use embedding tables, one of the foundations of
```suggestion
# In the section above we've learned how to use embedding tables, one of the foundations of
```

2024-10-02 17:49 UTC, iamzainhuda commented
need to fix the headings on the side, optimizer heading obfuscates rest of tutorial
<img width="308" alt="image" src="https://github.com/user-attachments/assets/5c0d9ca1-ed9b-4106-8df9-b3ed81985afa">

2024-10-02 17:50 UTC, iamzainhuda commented on intermediate_source/torchrec_interactive_tutorial.py
> +# few devices as possible for inference to minimize latency. \* **C++
the bulleted lists don't render as such 
<img width="867" alt="image" src="https://github.com/user-attachments/assets/032cef01-cfc6-41ae-8f5d-5347f465f5de">

2024-10-02 18:22 UTC, svekars commented
> need to fix the headings on the side, optimizer heading obfuscates rest of tutorial
that's unfortunately the bug of the theme that we can't currently address.

2024-10-02 20:07 UTC, svekars commented on index.rst
> +   intermediate/torchrec_interactive_tutorial
```suggestion
   intermediate/torchrec_intro_tutorial
```

2024-10-02 20:07 UTC, svekars commented on index.rst
> +   :link: intermediate/torchrec_interactive_tutorial.html
```suggestion
   :link: intermediate/torchrec_intro_tutorial.html
```

2024-10-02 20:36 UTC, svekars commented on .jenkins/metadata.json
> +  "intermediate_source/torchrec_interactive_tutorial.py": {
```suggestion
  "intermediate_source/torchrec_intro_tutorial.py": {
```

2024-10-02 23:06 UTC, iamzainhuda approved these changes
lgtm

2024-10-02 23:37 UTC, svekars commented on intermediate_source/torchrec_intro_tutorial.py
> +       * FBGEMM <https://github.com/pytorch/fbgemm>
```suggestion
       * `FBGEMM <https://github.com/pytorch/fbgemm>`__
```

2024-10-02 23:40 UTC, svekars approved these changes

2024-10-02 23:40 UTC, svekars approved these changes

2024-10-02 23:40 UTC, merged