[ROCm] Update C++ Extension Tutorial for AMD GPU
pytorch/tutorials pull request #3197
Opened 2024-12-20 00:16 UTC by naromero77amd

Fixes #2342

## Description
This is a minor update to the C++ Extension with a note about AMD GPU support.

## Checklist

- [X] The issue that is being fixed is referred in the description (see above "Fixes #ISSUE_NUMBER")
- [X] Only one issue is addressed in this pull request
- [X] Labels from the issue that this PR is fixing are added to this pull request
- [X] No unnecessary issues are included into this pull request.

2024-12-20 19:39 UTC, naromero77amd commented
@pytorchbot rebase

2025-01-15 23:46 UTC, naromero77amd commented
@svekars @malfet Can you please assign a reviewer? Thanks.

2025-01-16 00:01 UTC, malfet requested changes
@naromero77amd it's OK to reference the article at the end of the tutorial, but imo it would be good to incorporate parts of its context into this tutorial, otherwise, in my humble opinion, it's not very helpful for the end user

2025-03-10 22:21 UTC, naromero77amd commented
@svekars @malfet

My apologies for taking so long to follow-up on this PR.

I should have added more background as to the purpose of this PR.

The point of the PR was to just add a reference to the ROCm blog since this tutorial is already deprecated.

This tutorial is superseded by this newer tutorial:
https://pytorch.org/tutorials/advanced/cpp_custom_ops.html#cpp-custom-ops-tutorial

which in the December 2024 time frame I created a separate PR to add a NOTE about AMD ROCm support.
https://github.com/pytorch/tutorials/pull/3198

The NOTE itself is quite boring because there is nothing extra needed to support a custom HIP kernel in a PyTorch C++ extension. You just write a CUDA kernel and the hipify script takes care of the rest.

I can certainly move the NOTE to the conclusion section if you prefer that. Let me know.

2025-03-11 19:17 UTC, svekars commented
@naromero77amd  Please move to the conclusion section - thank you!

2025-03-11 19:28 UTC, naromero77amd commented
Done

2025-03-12 16:09 UTC, naromero77amd commented
@svekars There is a pending check-- does that require your approval?

2025-03-14 19:27 UTC, naromero77amd commented
@svekars ping

2025-03-19 16:32 UTC, svekars commented on advanced_source/cpp_extension.rst
> +    <https://rocm.blogs.amd.com/artificial-intelligence/cpp-extn/readme.html>`_.
```suggestion
A blog on writing extensions for AMD ROCm can be found `here
<https://rocm.blogs.amd.com/artificial-intelligence/cpp-extn/readme.html>`_.
```

2025-03-19 16:32 UTC, svekars approved these changes

2025-03-19 18:09 UTC, merged